<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<!-- meta获取csrf token -->
	<meta name="_csrf" content="${(_csrf.token)!}" />
	<meta name="_csrf_header" content="${(_csrf.headerName)!}" />
	<title>index</title>
</head>

<body>
<p>This is index generated by hik-ga-archetype-application</p>
<a href="./getString">getString</a>
</body>

</html>
